# Generated by Django 6.0 on 2026-01-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(max_length=6)),
                ('telefonoconvencional', models.CharField(max_length=15)),
                ('telefonofijo', models.CharField(max_length=15)),
                ('direcciontrabajo', models.CharField(max_length=50)),
                ('direcciondomiciliaria', models.CharField(max_length=50)),
                ('sitioweb', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresa', models.CharField(max_length=60)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='paginasusuario.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombreempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.CharField(max_length=100)),
                ('sitiowebempresa', models.CharField(max_length=100)),
                ('nombrecontactoempresarial', models.CharField(max_length=100)),
                ('telefonocontactoempresarial', models.CharField(max_length=60)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='paginasusuario.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='paginasusuario.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='paginasusuario.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='paginasusuario.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordebien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activarparaqueveaenfront', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='paginasusuario.datospersonales')),
            ],
        ),
    ]
