# Generated by Django 6.0 on 2026-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_academicos/'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_laborales/'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordebien',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
