# Generated by Django 6.0 on 2026-01-27 00:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0003_seccionpagina_alter_cursorealizado_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
