# Generated by Django 6.0 on 2026-01-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0004_experiencialaboral_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular')], max_length=10),
        ),
    ]
