# Generated by Django 6.0 on 2026-01-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasusuario', '0006_alter_ventagarage_estadoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconocimiento',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('ACA', 'Académico'), ('PUB', 'Público'), ('PRI', 'Privado')], max_length=3),
        ),
    ]
